### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by paulgeorge92** [davidemiceli/drillnode#1]
{ RequestError: Error: socket hang up
    at new RequestError (****\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (****\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (****\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (****\request\request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (****\request\request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketOnEnd (_http_client.js:346:9)
  name: 'RequestError',
  message: 'Error: socket hang up',
  cause:
   { Error: socket hang up
       at createHangUpError (_http_client.js:254:15)
       at Socket.socketOnEnd (_http_client.js:346:23)
       at emitNone (events.js:91:20)
       at Socket.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' },
  error:
   { Error: socket hang up
       at createHangUpError (_http_client.js:254:15)
       at Socket.socketOnEnd (_http_client.js:346:23)
       at emitNone (events.js:91:20)
       at Socket.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickCallback (internal/process/next_tick.js:104:9) code: 'ECONNRESET' },
  options:
   { method: 'POST',
     uri: 'http://localhost:77/query.json',
     body:
      { queryType: 'SQL',
        query: 'SELECT * FROM **** LIMIT 1' },
     json: true,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }

I am getting the above error when I try to access the drill

**Comment by davidemiceli** [comment]
Hi! Are you sure Drill was avaiable on that port?
